### ISSUE TITLE
Main screen

### ISSUE THREAD

**Issue by mccraveiro** [mccraveiro/uofbank#2]

**Comment by mccraveiro** [comment]
The menu as a card ui may make the user thinks it can be swiped. So we should change its design.

**Comment by juliooc** [comment]
Wasn't the idea to swiped the balance and the bills in accord to the user's account and bills and create buttons to go to bills, transfer and eDeposit?

**Comment by mccraveiro** [comment]
@juliooc Yeah, but the buttons right now have the same style as the user balance and notifications. So the user may think it can also be swiped.

**Comment by juliooc** [comment]
@mccraveiro I see. Is it possible to create an input tag with type submit and stylize it with css? 

For example:

```
<html>
 <head>
        <style>
            #submit{
                background-color: #ccc;
                border-radius: 10px;
                color: #fff;
                font-family: 'Oswald':
                font-size: 40px;
            }
        </style>
    </head>

    <body>
        <input type="submit" value="Transfer" id="submit"/>
    </body>
</html>
```

**Comment by mccraveiro** [comment]
@juliooc Sure! But why do you want to do this? Also, its better to not change the font-family so that its stays the same on the whole app.

**Comment by juliooc** [comment]
@mccraveiro No, I don't want to do this or to change the font-family. I was just asking if we couldn't change the style of the button in order to make it appear more like a button so that the user does not think it can be swiped. Do you see what I mean? 
Sorry for the misunderstanding.
